prefix = "Dev"
rgname = "RG"
rglocation = "East US"
vnetname = "vnet1"
subnetname = "subnet1"
vmname = "vm1"
vnet_ip_address_space = "10.0.0.0/16"
subnet_ip_address_prefix = "10.0.0.0/24"
vm_public_ip = "vmip"
privatenic = "vmprivateip"
vmsize = "Standard_D2s_v3"
manageddiskname = "mdisk"
nsg = "nsg1"
username = "CHARAN"
pswd  = "Viratcharan@1995"

